// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO32eQVXrU4JuDD5cizjEQAETtteW4zgQ',
    appId: '1:267287247981:web:3ba75e0282b6d31a635364',
    messagingSenderId: '267287247981',
    projectId: 'rozana-grocery',
    authDomain: 'rozana-grocery.firebaseapp.com',
    storageBucket: 'rozana-grocery.firebasestorage.app',
    measurementId: 'G-YQ3M0DQTP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_uzOkfrf4f4U0bPkw20GWW9OYBjhavoY',
    appId: '1:267287247981:android:bc802a2665e31350635364',
    messagingSenderId: '267287247981',
    projectId: 'rozana-grocery',
    storageBucket: 'rozana-grocery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp43jTDL6BbdDv66GhltbJZ2utsVCIzW0',
    appId: '1:267287247981:ios:bec41aaa65443890635364',
    messagingSenderId: '267287247981',
    projectId: 'rozana-grocery',
    storageBucket: 'rozana-grocery.firebasestorage.app',
    iosBundleId: 'com.example.rozanaGroceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp43jTDL6BbdDv66GhltbJZ2utsVCIzW0',
    appId: '1:267287247981:ios:bec41aaa65443890635364',
    messagingSenderId: '267287247981',
    projectId: 'rozana-grocery',
    storageBucket: 'rozana-grocery.firebasestorage.app',
    iosBundleId: 'com.example.rozanaGroceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO32eQVXrU4JuDD5cizjEQAETtteW4zgQ',
    appId: '1:267287247981:web:55d0a5f3e37ecbe2635364',
    messagingSenderId: '267287247981',
    projectId: 'rozana-grocery',
    authDomain: 'rozana-grocery.firebaseapp.com',
    storageBucket: 'rozana-grocery.firebasestorage.app',
    measurementId: 'G-XX3C6GD1TY',
  );
}
